#!/usr/bin/env bash
#Infinite loop
trap 'echo "I hate the kill command"; rm /var/run/script.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'rm /var/run/script.pid; exit' SIGQUIT
echo $$ > "/var/run/script.pid"
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
