#!/usr/bin/env bash
# This script is displays the time for 12 hours and 59 minutes:
while ((i <= 12));
do
	echo "Hour:" $i
	j=1
	while ((j <= 59));
	do
		echo "$j"
		j=$(( j + 1 ))
	done
	i=$(( i + 1 ))
done
