#!/usr/bin/env bash
# Check for school file
file=school
if [ -e $file ]
then
	echo "school file exists"
	if [ -s $file ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $file ]
	then
		echo "school is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
